AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: serverless-demo-lambda
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
